### ISSUE TITLE
Azure not collecting data from subscription

### ISSUE THREAD

**Issue by angelzamora** [Azure-Samples/azure-zabbix-templates#1]
Hi,

I followed the steps which are clear and simple but my zabbix server 3.2 is not collecting data..
Any suggestions what could be wrong or how to test the templates to find the break point ?
Thanks !

**Comment by karataliu** [comment]
@angelzamora 

The origin template was generated on zabbix 2.2, and I just verified it can work well with zabbix 3.2 .

I've uploaded a troubleshoot guide to [wiki page](https://github.com/Azure-Samples/azure-zabbix-templates/wiki). You can have a look and see whether certain steps works from your side.

If you would like to do future debugging, you can go though the source code directly.

Basically the logic under `lib` is responsible for communicating with Azure, `bin` & `conf` are for talking to zabbix.

The diagnostic data would map to zabbix items via discovery prototype.
`conf/azure_monitoring_agentd.conf` defines the custom keys, and files under `bin/` are for discovering and reporting.

Related doc in zabbix: [Custom key](https://www.zabbix.com/documentation/3.2/manual/config/items/userparameters) , [Discovery](https://www.zabbix.com/documentation/3.2/manual/discovery/low_level_discovery)

**Comment by karataliu** [comment]
Closing this due to no information update for long. Please feel free to reopen it if there is some update.
