### ISSUE TITLE
Zabbix not supported the Azure key

### ISSUE THREAD

**Issue by janey-day** [Azure-Samples/azure-zabbix-templates#3]
Zabbix server does not support the azure-zabbix-templates key.
STATUS needs to be enabled but it shows comment "Unsupported item key" , my item key is **azure.monitoring.discovery** .
![image pasted at 2018-12-18 13-07](https://user-images.githubusercontent.com/46011780/50258423-fe298f80-0442-11e9-9bb2-f4d9576844f7.png)

By the way, I check the connections btw zabbix server - azure, azure vm - zabbix server.
If I read the conf.json file in Zabbix Server, I can see the info about the azure and if changing templates to zabbix-agent from azure-zabbix-templates then the graph shows up.

I think the key as azure.monitroing.discovery needs to be changed, if not, please tell me what I missed.

p.s. I found out the troubleshooting in wiki , **/opt/azure-zabbix/bin/discovery** ran well, but, **/opt/azure-zabbix/bin/vmdiag query -s vmname1** doesn't work maybe because of key.

**Comment by karataliu** [comment]
@janeunbi  Thanks for reporting this.
What is the Zabbix server version you're using?

**Comment by janey-day** [comment]
hi @karataliu 
I'm using Zabbix 4.0, is that what you mean?

**Comment by karataliu** [comment]
Yes, this sample is only verified against v2.2 and v3.2 at the time it comes out.

I suspect it might due to the key format changes, would take a look later sometime.

**Comment by janey-day** [comment]
oh, I see.. That was the problem Thanks a lot! You're such a genius!
