### ISSUE TITLE
Discovery Error

### ISSUE THREAD

**Issue by dfranco87** [Azure-Samples/azure-zabbix-templates#5]
Hello friends, I'm trying to run the discovery but this is returning this error message;

Invalid discovery rule value: can not parse as a valid JSON object: invalid object format, expected opening character '{' or '[' at: 'sh: / opt / azure-zabbix / bin /

The execute permissions already have and are as root root (chmod) what else do I have to do?
I am using zabbix in version 4.2.3.

Thank you for your help.

**Comment by karataliu** [comment]
Thanks for the info.
As mentioned in readme `This sample is verified with Zabbix v2.2 and v3.2.`
